name: "Docs Update"
description: "문서, 가이드, 예제 코드 업데이트를 제안해 주세요. (README 제외)"
title: "Docs: "
labels:
  - "type: docs"
body:
  - type: markdown
    attributes:
      value: "무엇을 왜 업데이트하려는지 명확히 적어주세요. (라벨: type 1개, area 1개, priority 1개)"
  - type: input
    id: summary
    attributes:
      label: "요약"
      placeholder: "예) Docker 실행 가이드에 Redis 설정 추가"
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: "area 라벨 (1개 선택)"
      description: "해당 영역을 선택하고 동일한 GitHub 라벨(area: *)을 추가해 주세요."
      options:
        - label: "area: ai-platform — 추천·대화·임베딩 등 AI 전반"
        - label: "area: catalog — 상품/카테고리/검색·필터"
        - label: "area: cart-order — 장바구니/주문/배송"
        - label: "area: payment — 결제/취소/PG 연동"
        - label: "area: user-auth — 회원/로그인/토큰/보안"
        - label: "area: infra — Gradle/Docker/CI/보안 설정"
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: "priority 라벨 (1개 선택)"
      description: "긴급도를 선택하고 동일한 GitHub 라벨(priority: *)을 추가해 주세요."
      options:
        - label: "priority: high — 즉시 대응이 필요한 이슈"
        - label: "priority: low — 나중에 처리할 개선"
    validations:
      required: true
  - type: textarea
    id: pages
    attributes:
      label: "대상 문서/위치"
      description: "경로나 섹션명을 적어주세요. (예: docs/, config/, START.md)"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "변경 내용"
      description: "포함하거나 수정할 핵심 항목을 bullet로 정리해 주세요."
      placeholder: "- docker-compose 예시 추가\n- 환경 변수 설명 보강"
    validations:
      required: true
  - type: textarea
    id: evidence
    attributes:
      label: "참고 자료 / 스크린샷"
      description: "연관 링크, 캡처, 명령 결과 등을 첨부해 주세요."
  - type: checkboxes
    id: labels-check
    attributes:
      label: "라벨 적용 확인"
      description: "type/area/priority 라벨을 각각 1개씩만 선택해 적용해 주세요."
      options:
        - label: "선택한 area/priority 라벨을 실제 이슈 라벨에 추가했습니다."
          required: true
