# docker/prometheus/prometheus.yml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ai-recommendation-system'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  - "alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Spring Boot Backend Metrics
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'recommendation-backend'
          environment: 'docker'

    # Health check
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*|process_.*|system_.*|tomcat_.*|hikaricp_.*'
        action: keep

  # ML Service Metrics
  - job_name: 'ml-service'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['ml:8000']
        labels:
          application: 'ml-embedding-service'
          environment: 'docker'

  # Redis Exporter (if added)
  - job_name: 'redis'
    scrape_interval: 10s
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          application: 'redis-cache'
          environment: 'docker'

  # PostgreSQL Exporter (if added)
  - job_name: 'postgresql'
    scrape_interval: 10s
    static_configs:
      - targets: ['postgres-exporter:9187']
        labels:
          application: 'postgresql-db'
          environment: 'docker'

  # Kafka Exporter (if added)
  - job_name: 'kafka'
    scrape_interval: 10s
    static_configs:
      - targets: ['kafka-exporter:9308']
        labels:
          application: 'kafka-broker'
          environment: 'docker'

  # Elasticsearch Exporter (if added)
  - job_name: 'elasticsearch'
    scrape_interval: 10s
    static_configs:
      - targets: ['elasticsearch-exporter:9114']
        labels:
          application: 'elasticsearch'
          environment: 'docker'

  # Node Exporter for host metrics (if added)
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter:9100']
        labels:
          environment: 'docker'

# Custom metric rules
metric_relabel_configs:
  # Keep only relevant metrics to reduce storage
  - source_labels: [__name__]
    regex: '(embedding_.*|recommendation_.*|cache_.*|circuit_breaker_.*)'
    action: keep

  # Add custom labels
  - source_labels: [__name__]
    target_label: metric_group
    regex: 'embedding_.*'
    replacement: 'ml_service'

  - source_labels: [__name__]
    target_label: metric_group
    regex: 'recommendation_.*'
    replacement: 'recommendation_service'

  - source_labels: [__name__]
    target_label: metric_group
    regex: 'cache_.*'
    replacement: 'cache_service'